require "main.modules.button"

function init(self)
	msg.post(".", "acquire_input_focus")
	local position_fn = function(i)
		return vmath.vector3(300, 700 - (110 * i), 0)
	end
	buttons_init_clone(self, "button_proto", 5, position_fn, function(i) return ("Level " .. i) end)
end

function on_input(self, action_id, action)
	buttons_on_input(self, action_id, action, function(key) msg.post("something", "clicked on mouse_hovering_on_buttonslevel '" .. key .. "'") end)
end
